packages:
  - apps/*
  - packages/*

overrides:
  brace-expansion: 5.0.9
  nanoid: 3.3.17
  undici: 7.29.0

allowBuilds:
  esbuild: true
  workerd: true

engineStrict: true
nodeVersion: 24.18.0
pmOnFail: error
savePrefix: ""
strictPeerDependencies: true
